---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: continuwuity
  namespace: continuwuity
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.36.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: ${TZ}
    image:
      repository: forgejo.ellis.link/continuwuation/continuwuity
      tag: 0.5.5@sha256:467801ef68a22772147ac6088976d5284ec9f3a2182f004a8432ceb3af7a2319
    workload:
      main:
        enabled: true
        primary: true
        type: StatefulSet
        replicas: 1
        strategy: OnDelete
        podSpec:
          containers:
            main:
              enabled: true
              primary: true
              env:
                CONTINUWUITY_SERVER_NAME: matrix.${INGRESS_URL}
                CONTINUWUITY_PORT: &port 8080
                CONTINUWUITY_DATABASE_PATH: "/data/db"
                CONTINUWUITY_ADDRESS: "0.0.0.0"
                CONDUWUIT_ALLOW_ENCRYPTION: true
                CONTINUWUITY_ALLOW_FEDERATION: true
                CONTINUWUITY_ALLOW_REGISTRATION: true
                CONTINUWUITY_SUSPEND_ON_REGISTER: true
                CONTINUWUITY_ALLOW_LEGACY_MEDIA: false
                CONTINUWUITY_WELL_KNOWN__CLIENT: https://matrix.${INGRESS_URL}
                CONTINUWUITY_WELL_KNOWN__SERVER: matrix.${INGRESS_URL}:443
                #CONTINUWUITY_WELL_KNOWN__RTC_FOCUS_SERVER_URLS: "[{ type = 'livekit', livekit_service_url = 'livekit.&{INGRESS_URL}' }]"
                CONTINUWUITY_NEW_USER_DISPLAYNAME_SUFFIX: ""
                CONTINUWUITY_QUERY_TRUSTED_KEY_SERVERS_FIRST: false # NOTE: this is because continuwuity only supports Synapse as trusted key servers
                CONTINUWUITY_QUERY_TRUSTED_KEY_SERVERS_FIRST_ON_JOIN: false
                CONTINUWUITY_FORBIDDEN_REMOTE_SERVER_NAMES: |
                  ["matrix.org"]
                CONTINUWUITY_FORBIDDEN_REMOTE_ROOM_DIRECTORY_SERVER_NAMES: |
                  ["matrix.org"]
                CONTINUWUITY_URL_PREVIEW_DOMAIN_EXPLICIT_DENYLIST: |
                  ["matrix.org"]
                CONTINUWUITY_ALLOW_ANNOUNCEMENTS_CHECK: true
                CONTINUWUITY_REGISTRATION_TOKEN: ${CONTINUWUITY_REGISTRATION_TOKEN}
                CONTINUWUITY_CONFIG: /config/config.toml
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${XXXXX_IP}
        ports:
          main:
            enabled: true
            port: 80
            targetPort: *port
            protocol: http
        integrations:
          metallb:
            enabled: true
    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: /data
      config:
        enabled: true
        type: configmap
        mountPath: /config/config.toml
        subPath: config.toml
        readOnly: true
        objectName: continuwuity-conf
    configmap:
      continuwuity-conf:
        enabled: true
        data:
          config.toml: |
            [global.well_known]
            rtc_focus_server_urls = [{ type = "livekit", livekit_service_url = "https://livekit.${INGRESS_URL}" },]
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          gethomepage.dev/instance: "internal"
        hosts:
          - host: matrix.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - matrix.${INGRESS_URL}
        integrations:
          homepage:
            enabled: true
            group: Default
