apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: continuwuity-main
  namespace: continuwuity
spec:
  parentRefs:
    - name: envoy-external
      namespace: envoy
      sectionName: https
  hostnames:
    - "matrix.${INGRESS_URL}"
  rules:
    - backendRefs:
        - name: continuwuity-app-template
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: continuwuity-fed
  namespace: continuwuity
spec:
  parentRefs:
    - name: envoy-external
      namespace: envoy
      sectionName: https
  hostnames:
    - "matrix-fed.${INGRESS_URL}"
  rules:
    - backendRefs:
        - name: continuwuity-app-template
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: continuwuity-well-known
  namespace: continuwuity
spec:
  parentRefs:
    - name: envoy-external
      namespace: envoy
      sectionName: https
  hostnames:
    - "${INGRESS_URL}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/matrix/
      backendRefs:
        - name: continuwuity-app-template
          port: 8080
---
