apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: {}
configMapGenerator:
  - name: continuwuity-config
    options:
      disableNameSuffixHash: true
    files:
      - ./config.toml
