apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: continuwuity-config
    namespace: continuwuity
    behavior: create
    files:
      - ./config.toml
generatorOptions:
  disableNameSuffixHash: true
