---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: lan
  namespace: multus
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "lan",
      "plugins": [
        {
          "type": "macvlan",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {"dst": "0.0.0.0/0", "gw": "192.168.0.1"}
            ]
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
