apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - frigate/ks.yaml
  - homepage/ks.yaml
  - homepage-external/ks.yaml
  - wg-easy/ks.yaml
  - mosquitto/ks.yaml
  - fireflyiii/ks.yaml
  - hass-external-service/ks.yaml
  - fireflyiii-importer/ks.yaml
  - truenas-external-service/ks.yaml
  - piper/ks.yaml
  - esphome/ks.yaml
  - gatus/ks.yaml
  - reubah/ks.yaml
  - chrony/ks.yaml
  - firefox/ks.yaml
  - music-assistant/ks.yaml
  - ollama/ks.yaml
  - whisper/ks.yaml
  - outline/ks.yaml
  - openspeedtest/ks.yaml
  - valetudo-external-service/ks.yaml
  - filebrowser/ks.yaml
  - authelia/ks.yaml
  - lldap/ks.yaml
  - code-server/ks.yaml
  - dockerregistry/ks.yaml
  - home-assistant/ks.yaml
  - grafana/ks.yaml
  - hypermind/ks.yaml
