apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:V26bYHWmQwKxsHPpyCDAifW+kd7C0GeCNNHFFKF8czBhF4sMCFG6vHJ6ZbI+tGUhH0vA+es8+mFeamJzOnjfPMdvRwgYxI2Ld5C7/+5ZIMGr0D42eOGz8W4naRhHoMgFHzldUv824chJJxIIZf/blIs/+/DnWKpfAdf8zKJJpjfTM/hyL8uosG6TuKLT8d2sJa+tX4Ui/UOis22HdjBKxyJTLQqxpaiNJAnjdG+15Ad361arwwZgsMbxvfjjS/8mTdKjkJIlRs1QYXu4EEv1mHowJq7GLaXaoPmA4Ac5vFNLEUIgaHXghs6rOuyZrBFUQznCROWFJJAOeFD2RiBO0wBXQ0BFchMVhCBE11Yk+//CIDpI+2Tj1DQ3obXXuyf5,iv:jbwgBwtgIUzg6ayzqnWObEefhDFO9svwhUHsJpaSR0c=,tag:TsxHqfJEwNClVPITOFgM+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:fqKCAfxxwv96b987GZxFIjWCofNJT5DUHR1xxCaZcTRSXAdVIY7JIjsrxyDFV8F3AdSPg9uN9z2jXXKEUegcLpTCRUDWDcC6mZFNzkD+/8/qf14XeTrLH90y/farYD8RAwvjWty5N39K594Ra3bcLFGkFj+4qAMGcy7ba+DRJXYyJUJ81jOehVA6NtH/P1XAe3w3uWYelGtIkHQllV5vpFkF+DZpz/AIYAf/xEQAdlbAIYru1GzZQcceiIGlIeLVKBWejTy0wgqhMrNAoQ==,iv:zBPZ8lW53lTyJOzuLYZTBogYqihrtK8uzUZKjZbSkEo=,tag:7PhrY+aAQBZ0+usTFCGoxA==,type:str]
    known_hosts: ENC[AES256_GCM,data:6mamcSbyuYRyv0/mnBzG5HsIUPlimCGTAwpaTcFnmLw44HpWM+hBAJz+J0hQcp727mZDg3ZemR7pvUqvVhq4oiYeWOe3cXFKSVTK8ExydbsiTWwcBV2H4PbK+1hQsulbCZM5kc/geHyQM8ooaoIMRbfMFTanuZSkNqFyH7B8R6hzaibmE/P8Rf6MvEM4tZEvoNuERRyOs++9sbskH3Ixq0DVxmAyOUzOI1zD,iv:IUFsGVDRzsngpul33Q4v3DZ8GzTznZzYeUwFhU+iyEE=,tag:It6WFgecpO9TgeN4JGF77g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcjlKL1JlaFpJekJDSWJC
            R3ZaL05EUlZKdk13RUZYUGR2a3FHZTNXRVJNCmNTUytzZmI0SXZtVWZieVRySGJa
            WU1oQ0U2ek9ISVROcFczU1psS000VGMKLS0tIFRiWGtSR2lVUEFWRGN5WWpSWEVV
            bXp2czlaZ0ZQY1RPQk5vVllOUjB6L00KjX6fkvCpo5PACuPveIqmz9B0tmcw6zxc
            NTjhTos7kf09BfAE52mj3MfLSSqUQb5hHxxGAEWN9fiLTHDmM1Ny7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T03:12:58Z"
    mac: ENC[AES256_GCM,data:KJxICo1s+oFmkAVNmd7N0KcrF2tq5E+gqIAmsasv4Oo8ka6nt/B6yINwfZMjxTDEIcJzkAY6DFBhXben8lGKfkQsObvVa6J504rg1vza9wln3xsofexuMQWN64VuDBhK6Ws7WjHs6+2PPlCU0pU14crTGUmlvA86332Hl4mU3+g=,iv:ko1xitAxiksGSqb9mx1mL+akmT3CRWEkHnUZ2IKE/+g=,tag:yvs/ZmaZN25XedxcT1fjGg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
