apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9cuj1ENN4f9mAlZvMYAafvIbtpTJTtBfbYL0ADEBXUreC4UAP5FbIs49oIFLXpXJMdw3HoRHb2NivoKVov7XqrzZEi+MQ4ZUBnHtXVc2xJ1maykvowwYAmpZWIs3LLHTzkpD489TCnRvTEWMLJtigBpjUCtdXjL7UKue11IsJPHE2F4egmH2NNsPJZzw7/k1QpkqThiUf411rLLIDxyq5G+Kxyc3+DcFIWN2FEkHOripWkNCqH/y0qysWi5K70pIYiaIiFiJjga1nFWgmSuae0EwCCfOFYN06JKPCWeUfX7eG73NRgcHREappLsaRAsNgsxNE9Nczj+umCauNL2Rokkb27YXJBjnGJzK0sDivBcMSQ8srlPmTXPbMSG0laXq,iv:T7azFBIz1kQa1ttlYnL4kZzKPWUv8JnICkiKL7HIIPs=,tag:rlB5I904K1HHqMc6wuP+dw==,type:str]
    identity.pub: ENC[AES256_GCM,data:/wvcI4MG5UtRcUnbc7afq39b1sqVuwPmR+QbjnsgsLKMB8/Y2FPytUxpRKJJluwc3xJoD6Hr05jJCkD9sJYYBOzfTF59k2Tw47ZvQDi45mt29rEX9yXeU2GL2waYj4zJBaVWb4Tl86ZyB5+FlzooawQXG828V/J/oZ/3WxQmMPrxHh/+pT1ibbzsXkc+OmmuoRcEECxVTzkI0rZbN4T87MBMS7iJeHsWjd6MoiqboM/TaOuuCrcvP7zFDDV8xYtVWlNJwg6JJ9PKSettfQ==,iv:ETSQcONcSR5LBfu3858R7Tj+n++fxacRS7vjt5iIFL0=,tag:dCLQdQxYw6pWtXp1ykjkhw==,type:str]
    known_hosts: ENC[AES256_GCM,data:pu32rHex4bCo90KuTCuAL2R6+XFgbHR9FPnKkAt+NYqbnGzxtyZpoQPIzZxBRIgMr4DJRrf69zahMvyvuEzXfc7cKGbt/g2oPbRL08t8oQtxL1ZNj5dZEl1wr0yo82dc1t1MMlXhEymOQ/YiK6P7BedAEP4GSRMALvpXtP3HZDcS0BAXQh2qlAuc4BnMO6/Mt4P54N0mQ2a4znzBVEjzFCT38w23E07kygM7,iv:IRA1jA90I+asEcN8MB8+gXWBwbLodZGldjuUw/Sg4tg=,tag:Gr1hDIhPrdbTxJWYn3I3lg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL1R4eFYyS3pTeU5VN1Nq
            UWJyVHV2bjZlTmhhbUxYdFBYaXBZT3ZCeW5zCnUvUEtqbmFrWWVsY01RR0FmU2Mv
            T3ZmNWNmQTR5OFowZDZ2bzhoeG0rdnMKLS0tIGlpUU9uRlpiUjdZdU1QMzBCZGE4
            OHhncTJkNjFnUDBiNERYZDNGTk9sdzAKLWfYXkGHDjOXab9HHlpAS2FTxeyoj5fR
            4aRqTwnR4aI70mVQc2yDLPaWHrkPJOmsWg+WFzKEK63bD4u/m5SQug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T03:33:50Z"
    mac: ENC[AES256_GCM,data:ZX4S8dJ04EK0/nt4ze8V3sWBHAfoAIcJSFQU4gBnmJNwkH62/dnvOi0fdAsKYdEzf58cBRfr1J9GL7ns3bVtQWpVtgTgwDY7Bb15q2Ze3yUW13URmwUfr5v2//rjuADi+H9/k8mrIgnZCJbjVOimCR0GgoLekvTfVGPFTHNFfTk=,iv:v6jl5LiNfHmimF+OULwWrLpe0CPfd0tRwFYe7SVnKfE=,tag:5sovk3jF53/gRCzDCL4RIA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
