apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pTPAz32VXbzcY4iDIksSMEP6Lk4xCoYori7JHsV9pFQbXaJucAm0eChJ4w9E3PLYDx3QG2PBmR2VT9OP8cRFYu2V3fgnLHaDxokekTt7Usy24JxNp/33/0qIGhRL2G1tsXSMcEGju250YXxs1Bw56i2CMH5ZXLq3HGnjN8EoWkPB673tQJKvG2wVR1vuTNdakT8smpQW+R8M8N7r7BP9vr+x63V3RSSouRFyeZ1DbaUQi90vPgYJqD0U7kclaTTWtuP8OEKDLCOjjcr2xrDvour4YJ/W9FNj6r0KajL/IKSNJao3FomgFjSMyJkGze+ZHx2NGgW37sC91+ijfjIzJiO0Graf6PX3iUlQ0zyp8feZ6V9RA2MJqcVdwg7DbEGR,iv:TN2OZXVgDHlSKjLaCMO8HQK+IRegMFYeqvFB6qCWjgs=,tag:HarQJRNqkTcBANIAmIZ66w==,type:str]
    identity.pub: ENC[AES256_GCM,data:5+r+LE93yddadWuOYOx/k8LkPNquKKuqMxa2F8/U4zyZNEz706380MuYWKPhGygldmwbCxj41ynsR7RR7mww18mQNvjznyUPd/JmPcDQjoGWhdO8V4Nw98VWwrtT4Lm9wvMOLcPv+ydEu7mzBWWqTun4qGQEZcDRwDAfjhWRDyTvzQ8RM/u0MRkLueD4eTUuy+125a/VP2rF1Qd4uhqg3J7vvB2d1HQncKOj7vl7wPajQBRYp/ijEyD7bv5BTUksSwToOjJO4BKr01sq8A==,iv:6Hg18/1FZnuyiep4S5emdYiiPRaqKh0k+QVZMawcpyc=,tag:3zRPxq0UbaQvfoxzQkm4/Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:mwqorBCRgkF0766xAh2S64O3NhqSv//9GostKT0bOxmrSLsXu+uGFxxFU5n3t3Wut1VWA7CPirJsyOs4qhu86fWn45Rf3lZn6+r8626EM9DP6snhFP0CCWk8S8mWW0DHeZpmG22Av7DtkRX3Qr+Cs6otfufLPX5f/ECaUF9FQ2YtlECHlUbzDZta40+4aosSvRLwf37Ioo/pwFM0Tu6T3DvXfbdTVTXizwYm,iv:aPDommNa9PYRzuHvUnA0LGtfR1Jl0re7q9ZTyATNWPw=,tag:PfZAXFUW6LHmrznx+9zebg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkalNsS1pCMGNINEtXYVlO
            MlpNcHlHRmkvWkN2SFpCRnpCVHZFRGswemxVCndzY0VnVFVOZldRZGVUS2k1Skcw
            Y2R3VFdoWStHdmo0bmhmdjc0SjUvVkEKLS0tIERVNlY5TUQxTjFjRjZrN1dGVTdq
            aGhKUzN3dW1nOGx0Z3ordFZUY1ZnQUkKfD/I40bPDOxFdnoa7qtjfXoHxPA+ak3e
            h95F0erxOJF4I4azzor7SkrmeY85iTxOMSlM6fcb51ppB/SxsPKJwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T03:36:38Z"
    mac: ENC[AES256_GCM,data:PlKd7J4i9bryh0gKdY0o4soN0eLGaa9DkbDK4+7JbJiC0MMDU9FNRXiqZVfvsEm8bgomMKG9Lam0Rn2598ANn6k9TuTC2mMDGq8haXEBJ3I7pRfogXNiVq4ed5goE/o0tdodRWDZ515lGDKGOFyINcKFLwwnU7IGE17v+ftXADM=,iv:nd17LXXaw1fJxgwX6dI8v36+boIxQQ1rKoxtgtCb3Io=,tag:CPbvxxsc65Ig56TjW20u/A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
