apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zoB1mizAqlLpyv72RH9n048U6ZxslituxX1caVVnUWmMvNalbpd6DrPEyrQFLntNpBQOzjf1bjuwLokTLJ2KlWqserykqSdYiUb3K5IHZ5z0ACkqKyPCMCNXUWMzHvj6O0frDfK1WD+R0aSE21J+GAf6ZD00PxjkPU2BAp3POGGu00uOOUAJdbTlOdqJrxDaSBZ806Hj7LFBnnKVAf5VG9/bMcv/Edm5pbq8kzQ7YsCTWPgVfLhJh1a/G4QKdOJ8/3WqiEu6XGFLDhXdV8E+ujEc98AS4R7DpIaYo5tv9hF/tFYaaLWE5GgZMwOeQHoBCQa4FH7TjtB+Fbd/i8Wz0NNqMWETZbwTGV+dTL9FxqvhBjZ9212dbVWxRkWcWh4E,iv:6S/EkcA+p4jtGVib1HV4wEgFeofVIxx3J2lwsd6/XL8=,tag:U+mhCOgdc0317YKQ9h85BQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:jHf/xDegkysqYTqLbcUlPZIjWMxHDyuUUy+6+pk3leBZ4myjOS6d+z2el51WgTcJwCvjzoMNYjkDV+37vyRldAdnirUaq8t9Zw4UGo2Rsc07p4vx5YjRMqQrDARnIhYjtXLT2Vs62q4SxjivhYGdRr6Qv9bzxHBLHTF1GiDCeiQvYRd/BM3iwXIi33BpcNlx3MnAryCOTnMgnizSLLavEMnG/66jHOgkQsBvLZuCS+sB2ztqQ9M8ZDoDXjkzDV2uR73sPfnn6RDkuQevJg==,iv:nG81inEJs7dPOw/750oSzSU/7JNu6MYY88DgqMauDCQ=,tag:WVjfcLLfLs2jAkv6zezGoA==,type:str]
    known_hosts: ENC[AES256_GCM,data:w/bXIRSSURkZpul1yyzYhKtKyg+bwxAo6dw6NTqVGpVwx2EQp2p0zBvb3q+tr6g3TJllNe1g4TJ2M3OygDlyI1kzwQvtJJDMXpnuMLO5bWrBd3/drBgMoPZUMjfBMPFZ62++oQTLqbzBKOM7L36T2ReCdLVe74axL91Y0Mi4wQetoBk4PiA08+pf4sEvcPNqf03siNlc59Yi3dq5MqKsv6tB8f6a9lJw3BK0,iv:5LQXtEiQcRWup/xX3eziOteGln+LtWnRKXKmLazajhI=,tag:MEhR3uzkzA4pC+xYUPO70Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZXFBT0lOaG0vaTBMMVRQ
            L2JvZmc0RlBGTG0vSVp5cUZBMmNGN093b0QwCm5jQnFuY2RGNjVPbWswaE5WSitG
            Nm8yOWhMdVBjV2hodktyOHVUTXVrU2sKLS0tIFFWRDJXUDV3UXlrTjlZN3hobENm
            UnNrZThmVXBrV3hrSG1QRm0yMytpK0kKm7q+M5UFg8ZygPuGFOrFmE8RvsmYvbuV
            BYww6MAXkbCUjdJja6tixLkPzuwR4UCYQqkqstWBAmMeIGyncVTU8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T04:00:41Z"
    mac: ENC[AES256_GCM,data:es1YJojW++FUML/RsiTWm9ZwD1wprCs0XHvHBRuZu3vtzr8lTfBiscBJjT8N2cRkiIdhe+VKEp87IkVu4ljdClXxlgn1o72oud90HI2EPUZxRjXiPMOs5XAjbWApJa+NzGe7IG95lCDjo5x55dr58wzJd2FHsXJMoKlXfOU8e3M=,iv:D9MWZclQfrB4ZpelPHf1Nza6BVx+KhbvIO1L65c43gI=,tag:1/gAq/bF2CObM7HDnxqjHQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
