apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wLMjeEdW0liIPKC3faFlADb7oFLjO8v6uh93urxJxd00ojWtDPT+kXg/6WHzOnydwCCsORRop7kB171yniT0Gmo669e1EOXzUuyTfpZvpA0X4sklhr0aqwJZ+5Gi7PKnw5Nl04Pk0ByPEyBuPxKXntS9yBQeBmjyYKc9s5HUm/mQCFNfGy5nZgDK6GoCMDnSh7nro0gCfz1/PEP+DjuT2WF86/qfiEm2EphrNOxfBPiXvcRq2ONmgG6W88CjPlTNZtkWWb357dF596Vi6/cNsYAuq+cuJPwuyFAaR3fdWH2Q4tuR47KmW3KtRccmma/BU8xJCHWVfduA+qpLs/JXkQ/k6mfOhQMBkii/pFmatj2D1oJGfNvtsGFluO4gr96C,iv:CZYfwceVixf/W7rSklAzue7FsOcAt2zvRZYTUl7Z6Lc=,tag:PpCQcjExOkK255n1psEgnw==,type:str]
    identity.pub: ENC[AES256_GCM,data:iS1MxXuq6wsHR27MdSGc+4UcjwvBI9qOSuLA/MkP8DWBzRe7OEmP8X0p6Q+bW0wQ/eC1OyqGCPXxYR5UamLTex15eUuIH+nX8XGMF84qbTOm/rl5nN/F97HjVYWjDVFmJSUyExBBUrCUJQKaklrTP7JfQ7hAyf4SGo8tqVfxBo93sCv/7Butn+vgtS/44GJmUN+esnCavV5rymk8ZqxLKjZ6WLzebToV8JrX5h4pL2m3s6XMSzGU0JUbXtqVuaRiiAVVoC/YYxqzpmE7eg==,iv:NZVBeqFMAF3z7W4uU/b2Bj3wRiK5Rt3Cq/yNV+x85+k=,tag:gxQmXJr6eqJfARC3vPkWkw==,type:str]
    known_hosts: ENC[AES256_GCM,data:bhjRghvmPhks1jRPOk/TapdkrKHeiRwskVVAi7sxywelWOnvrvL921i1wIonOsxbsKqI8TegcdF6mJbOvrb38/NpNRSjjl9BLJWFYqq8wE2drdtNbStActZoK3fSthI3sNFEPP4iLPNQtv8MYhY0CATJqfyU0dwY6931GGJtUWokZ2ECLLGq98Znrf4syZNiliIyYfAgQxfItf3fwL3+40572iUiFE1WrvLC,iv:WLzf64J4S8MAxmJps1sh8Hbqg2eCHnDLR4OnRG2Kgy8=,tag:H3h5JPzDl0mdU/fbfEj9Mg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFLzR2SVg0bE9kN2UwaWpk
            TThVdTJUWGdzcVJkaGtkdTBYbFlRY1FValdvCm9EMEQxcUgyMjBkWmpsNGhhcGZl
            bmJoRXNQZDd5bSt3M1c4emxQY1RUeXMKLS0tIHF0ZUxNKzY4Qk9HcnpUNHNSdk1n
            WlB1YnhnREk1Ym9vNWtWaVZZMTZiaTAKBEIxOcFW+Id9rssu2ZM1Y5M3Avbd8nQX
            DbQHtHF8HIN8NRbN6pcjZotI7fmJ4tPbACBpydS3GoRZG4+VehKPHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:26:38Z"
    mac: ENC[AES256_GCM,data:DY/2Am/C6VCJ9RrYDdzBTJrxrwm9nzy1r+yuIUEfJX2A8wDQAkK6PE56CMxUVQ9B2UK3+IkJ6qdUlyVeQXffFHeCviqfOqk2G3wvsrK2CqRl0P4xc7wUUS+aRxHew7JQ/4yo8ma8gG3WRkQ6GiXU0VxK5G62fOtuRs8hWhEMtkk=,iv:ahkZmK6V/0rjRWwZYk5xQ9P+W/vFK4K/J6VJMWtegI8=,tag:OHSBldDNrwjC7EPtulVw6g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
