apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IEMrTKxmBRiS6TzOLync3LpzWCbTXZiAo4c+eBR8Yj/3CrbtZLm9vgDAcYROgMN4+VAt7vjSQMtf+4+YdMTOSQA4TuQCUTUKV/sRkNEKTn2GQuw44+/Ivzgy24Gexbxp0rffTcigc/4HRFnO95X9uzoaUZEXoWJMr1MZsBTvXM6TJczXLYR2I/boutcPzMzh3VmHLxiCyJZyyLzCiTnJl1rDTlxVAuhij5x3GJ8nEqEMjPLCje8n5lRTPl61Hej8ObbByD7htId3fNfbSLT2VVRrElQfo1/jnnZiUS8e5O3DULuGFpfrk6X09PqReMRRS56SqVCMGuzkPSAcOL4JAgNIfoJFNLCIpcKik9R62zDL9aJJJ455COyy/1bMnxra,iv:UsmS/3jaCeZ0ecDizoHI4WpTs04FHfpUDAOk9wey2wg=,tag:Qj0P0S6cSbIODYaF1ANvgg==,type:str]
    identity.pub: ENC[AES256_GCM,data:cvpI4alTvHFa+/o30GerhzwVXC0SMW/SuolKn8p9E8LADGIUWpkjABD7ev2ofOFxU34kJO8iU/9Wu0mCTUeQgmJ6NN4FtCjIg781UWmwCd8oBtlaa7QpH6WUR33SzFtwMoP8k2qlRrYUXI1YHJT8q8pDWIAc1ve9GqLT69N1lAHIhBF1lMDrbuVu5eV1AoctiQXK1G4TFB8NMykWeQsQVFqLqy7TvWIR+B/2NhAb5YeyaPSw/IDyujD6IW9Btyo+0MEeVFMi6ow3RP7wAA==,iv:okcTCjh2YFMXLfpyKpcwh49rtrLzD49EZ4/54bi/VZ4=,tag:ERmz5yU9ZuLGcHE7ILpz4A==,type:str]
    known_hosts: ENC[AES256_GCM,data:hpTKAsyViqAslNhj2mIAqifApAtBbe97Nrv+Jbwmu6crl6yN2gbUWNiAtBMCOLlMV1BIjCBla9EGFl4ebuFOYBStl2zm3QHwWqU7hR6jt09gJJ+hUsB8cdpsKMQUSL5IoZzr61BXV2LnLLTRr3nlYRPucA+Yfs2kCXfP+FPUQGgT7hElmnw8vQwyW9kSJGFNE4HXIletkvAAMjpu4B4qtgJ5b3PtFCcG4hNk,iv:dZLB0Gw+N7YyDUZ/Q5nYoZLpgxgFMbOVTL03RIKjF2Y=,tag:TxdYuEUHEpU6WUvMiDdMVA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z2RZcklNeW90M3I2NnRs
            NjBqcFhtWnhCWTlLWG04WGF0eHNmdGZWY0I4CmJ1Mk9zL2U2MnhXblhlbzJtdFg2
            QWxrR0RkS3Vjck5KbGhnK3p3aVg2dkkKLS0tIGFmUmJ3UDQ2cFUweFVGZVE0c0Jp
            THZoZ05GSXFsYjBIa1h6UW4wc1NaaEEKEkYN7AMf/pnDeySAGyBYHQBzdDhUdGlQ
            NXS/5Tmi6VstVv94fSR1iu6V2/luS+dXiP3PSh0Q9LYg21NwcS3/sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T01:38:01Z"
    mac: ENC[AES256_GCM,data:/poQ8sYUB+EPVFyOqYj/prCDrorZuAKioKaT11EXmFNXgb8owEBF46YyXOhkX69uvnmjasx7tCBCIAV4LFXMQyROfzEnbFdR03CoX1p4Kk5acTMuJiiDxOt99j2GQBV80Sb0m9x5XlQ3yjnw+0iY7mTDAILPrW001m5+BwzHJFU=,iv:4ZbkBlTDk+igW/x2eWR5SjE44Ha+ObA02kIKNGI9w2I=,tag:Wr0N9KXENVUBmC5WhMeFHg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
