apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6JvT3bAmY997NxtZ/tUPQjJsQWIKrL2OawPCezmNUlzP7gv+AilClzY9/+86Zs6dopZiiaNC3rE2ydPLizAi0c22eI+dZzYdY2Pn2LD5PCWbbKf5EuphncFX9V0eQWfsDfuNq10s9Q/IZ0m0da3uhxSWV4hXf6XNboqwmX5vf9szhugOaIG0EVa2uFD27JTx4boR7Kfo2lJ34IUVTYpD66YCZfL2ZMrWfOKn3bKQYeNTkG6woX/i31BKvhfEwjIhhCg04HPCKLyj838iWRUSISg8TxM/U7vAlTboRO2kmdXgufGaUtkpGXyQQ6pNOBv+mr3c7bUz3XWie3qtOAA+rTp07VEufBK8TeBJx2iLnNjF1fXEgW3Mw44/dV9McPtQ,iv:Yhtb1R+FiZwzHh3UfK3mz5NiKgEswxQk4CIpJshWQ/c=,tag:UzBQPWdfCov4va8t6yP0Mg==,type:str]
    identity.pub: ENC[AES256_GCM,data:QuJBwUdQ4unVTNS2XNPz8pb+GZwVzQJ16RsDi7zWY5Nyy04bmglL/5hBxcbZF0jMtOQDjy6eMN7p+DarsXHo/lY7JtZ1XI0FiMHZfdj5VCGVYojp5VsdzVl2VrOQoRhYKQFUSM3kyu/lo9nQSjAvPMbx62DKpAWYd4epnPfnJMTix4LyidfN9wBp1xLfO1DZO9ZDIwOXA14BUW4jFLj4l88XDBmfuy5LVs5+vVONdfQuBmJvpSULExSHeIKPzsMgjMoUixkc/Yil1U7wDQ==,iv:YAICuysBsgxceeI4mqQDhcDgP2SJt+hIBc7CqJaa1vg=,tag:SCXIjon0iyljXHfawqsffw==,type:str]
    known_hosts: ENC[AES256_GCM,data:YVZ/888v9MMMwlRL/9LCYHEEP1otQMysKuLZ2ZUfRXXY2K+1Te9e7gLsnBp6xw83Ex9cRnrQHKpOGhiqkk6MAUA9f7Vu+ttJfBlHCbmEyQfjenunfDTLll7c0R60fIcYXDKJpDLGyi+pRMZC5R+wFa/W+L7v48yXTzD+tyk5AUVgjzwYllr72K4QPwbk9QPOo6ILMaUP+WMOshH3FI5GrlCs1j68WYjky77M,iv:htvuKAyuDxMGyMPiN8zjEc90eEjuqnS5Jb6WeGFA2eA=,tag:gGutAW2oTP6mrkcWvV4bng==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZWNEYmtJRzdXM3grRitL
            RmtkZHBxOHljZS94T0xZMW04b3lmQmpaRFVZCmVRblZta0FkUGZ1bE9MalhiYnJh
            dXNHSklPRGRRL0h4M1d6MVZKZEgvRmMKLS0tIG4yR25kOXJJMlYzUVFMeERBdVdn
            dGdVUkxOMGRNaEVrclVCdjhjazIwa28Ktu0Xsns8SuCguXJibZLmYpMzEcj/b59e
            YfHwHIsCZHJYWuhu+ol10TM1YkUDZ6cgRZuBlWHYu62V5wm71nfRjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T04:09:51Z"
    mac: ENC[AES256_GCM,data:jtZBHsBWReLkbJCT/F0Bo2MIh1b2F5+VsXF4EeFt06Nl4YY5mi4FqPR2CCltPSIbI94u3p34bP2ROwbiIIli0zzcro0/My+rcglGlS6tYu9Hg0GYekIvc1KbHDe3u+h8fRj4Iolj2n3vmESizOhCJgvmve4CbLQm4p2rY1xVWqY=,iv:dWI7YaNkoAIa1LQO5iFplOb5Gd2taGRcYGfXIva2vl4=,tag:pDd5PPEfwms+0o9IMsnmkg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
