apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tSels/POBwYZbukdB6r6vsG9TxnBGUcKFIT79zZPtqVjC5/c/xBXp41cF50r5qNqWhfK5hIhW6N4EkM5Yr5JAz0HmtSc5UR0vpAjGFsudJ1BgtwntnstRYuh0oP6ru658/+Ef6k3OjtK6AeZq2zW/v5OdVfcQ6rAKUGAM+lRHnf/aXmZY0JBu+FsRMj5l7kIL2J5WqihBy+EckJfxM9Lcl1XuDN5HDM5jKyJz7AfxOS0AJEW16WeRBLMtq9HaEDHVz0avYAHyyLI3jH9frgCYfU4H3O0eYovPf3pCf6Y8bfoZdtBqoZpZhtul4j2KxvflS4KZAigb5mygT2iOXKlmFRM/5nH3vBV+T62q9tRQVmin5h2Wj/E7ZgAhMcyWBhd,iv:tnaTlRxcgxSGqINEM2OXt0mQpANcxpmaUN446x4GEZs=,tag:dSiEkm/uAQnQz7FngJCP8w==,type:str]
    identity.pub: ENC[AES256_GCM,data:6sgP/4CM8qpuaJcY9zl0EK3u7A7ttDr16Qu05HHlS2zq2ldWdNlPGFK4/xmQpY//YI18B4+wV3pK9Fxpm5homJx9o+yk3FBG8xIfkLGEKY7tqM0vXrlFlrD/0+j5roMViyQxlH1gyOFwGz6s1+tTvYL/3hZ8lAPof6getl4S622BLKRbPFuE7UuVFAb2NEbcQiEGpVAlY4Zvuxz+FvpngWIbMcHGEURueN8lnK6QU/jJS+Ons/bYdREEv/regi8sklgCNYjKvgqz1bdV3w==,iv:Cr6os92efcBoQ3SBywvWH7NqC5RSyE3gOTmMtnMD9Tk=,tag:jqUutymRJoxfFJA76xunbA==,type:str]
    known_hosts: ENC[AES256_GCM,data:CmVamcnaB3BHbMljjrdTuDd+IWet/8e9RbJr0JgkUkhzj3QNxN3tQTfpkIbafDiFt8lJMtWvy5cu7i8iQqL29kXCpypzE6k286wZJWjRmwp2LIWNkhvLJ4Pnkh5q7NF5FbXBb4bGPsCagU/4Z07AmI6e4nZ8rvW9v+X3kvpeGN18taDAs9us2k1EKFEjNzBVSVcD9LGeCS0e6dJQqbdPo0Drc8RFBBJRJaxj,iv:aBLvVEyIS/OjEwU3Rgiyeyl3tXgKtm0Xz1s0b3YtcXo=,tag:khG9Wv5Kapq21icRD5Vu8g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdWgrSTJYZ2U2R1BJMDFq
            b1dzMVF0dWJsTVB6R3ljanYvMUY3VTh1RmhjCitWS2V1SUhBaVFTQWcraXpTS3R1
            M0lIeXBab1pBVzJGR0lIelNmbk13RkkKLS0tIGl2VzVycGVKcm8vTGQ1c3RST3dI
            RHByR3RiT0lsMVZCTXRkZUMxVEY3d1EKli2/bNN4eBYWl6tqw/lcsW/q+SlxcPk/
            uXrbIe2Zq/wjhK/hoeEteXqUese6gjRirVxF4qyjteGi0//tYnQS2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T02:18:14Z"
    mac: ENC[AES256_GCM,data:cvpmCHfuDtq5kha3DEMR2563ztwe1aW4mHerOHRg+N2ne6/4vbtCldVI/eG+FJXMXYFj1SJM4JDebVCqP4E3QGaf1IhdbqWsPzQYxPXg1l8jqMiI6c510evxDO+6QI0OZVoCqFUEICelNfup7pMBUfKXds0VhE3jYl+fDbZsmtY=,iv:wDEEYHPgdAxKQx5XexvZ+0m39dAOsUC+yzt2l9BIkqU=,tag:4FjCBMvafGKXGGB1ssUGWg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
