apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jf+3hBsW1ASUnNzIA88S0vUI1tDcPlBOLxJaUz+92Ts4k03SUWopaDWBkEIvKCnpptnq9mwX9mDh/S7E3VKykSl8bgzn8AcKPp1lbxfAYwvHL7LEZ1+DmDah8F+TA6jnEXO6boJfs+o2yTgVOR6IM50MT/dAiGBjZmExVUS8eCRoRasDG7D/7gXtlxYtF/5nW45xGDV7QyzaHCB1zYaCDUw4EHA14HVB/vFupyWSzbnL/iBCaQpwsAh61DRgCgMIHNzRwjdM/6tIepiSSefwesOiAKbIce0G0fITQ9+ldYMYC/xw7T0QkoWb5/cSVLTFGfUQuFNc+PMOGmeFRrSdYssYCC2oIiTxRfh0Ma342lRuI3XgWVZpYbu1IRij69/N,iv:JIOlAKpAWCifWXUXS0O+3RMsFRyviOGlQuNnLfQuhEA=,tag:gijnVUJ9Kh3kD+XaJYinWg==,type:str]
    identity.pub: ENC[AES256_GCM,data:9MzkfNm5HDEUqZxCdOTgbqmKjppABW3Qtli8GdgRlUp4Zad/Od+j8fTkVxjk1/TLLqEqd9pgBuM52CoHZGNb27LfhAuqSAHZ6mfIWt7OlVKqgjJwL+E7iODhv9DFTJD6XWBiOBju6C7YkWIr1Rb2fzOVSCLsnl0BLhbL/1PMQ9SwbyY/ybTJGfmnokf08z1lwgwwdjDX45P6G60Vhcayas2HVM4J/rVxmztHlgKgYixBYvw+Gv+q0inX7NcNG970pjB+nJ1QfQTTEmOSHQ==,iv:/km3G3h+XT0LVDGZSAoh4GtHe7a6rYGorYn9WAJqFiA=,tag:B7MNOb7wB8bBxNmiAXwkfA==,type:str]
    known_hosts: ENC[AES256_GCM,data:54cssXCBkLr/X8vM9p4yXWezCZeSma6lP/RcJcSDhT4pXiPR/7UseC68DB5rvIw90oTUbhCMGhkPdvfkUurbsWoU6hbE5BkbSTnOPAoMkMnbAbSRsjamsR0QsbdK+UhzyA1HCjL8vNOEMMKe4Wz3GepT8RWOlwwhfytLeVcE3Zvr+3UVPPmSOcV7HjMDhBEi7FMy2D8Md70RPOfXEa7pmRSpFsmIjvSYAiqN,iv:3vbPlVjMZAVd56OtFXVg2k00W21/1/BqsSVNnv+OkSI=,tag:oqACDl1QShVdreKCXWwC6g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRnJmbndmbHVIckFjY25I
            bW9VUlY4L0duYk84c2psVUNuTmREWWZzTXhFClRjWFdYb1BQY2xhM1k0MWl2UWdL
            UDlWdGplTmoxbnBBNTFlbGNzV3Y5UncKLS0tIDZHbDhIbU1aRm4xMHFJQUlTNmxB
            ZDZpcS9uc1BtSVhSajF1N0hzV2QyWmsKEpUB359VPirNElHZenPQUWaltcUTpQvO
            ZdLDymnX36L6yRKvXMmB25uQcHlGpZooDb3ANbTcOp4cULSeaavFEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T01:53:29Z"
    mac: ENC[AES256_GCM,data:6L9XvKZ0T7b0n/W/9ULCRp0HYGcerUIvrFYK60RucwGnheedg//WDFsI1MVxsVAA6ICr09/n23O/4gQYX09f3e4hCQ9d+KhHGnSrPnXI2WVBvA0qIO9a2/yv30tz2hsfi8rNCRx/aiy1f4JVFGEc99gwfaOqbKKOcgZIiB9zZ68=,iv:E1zEikRhenypV1Lg7bpKhgbOKCv/SjO23YGW+/6bCrQ=,tag:AZuMY67Curo28Ur81jQg/g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
