apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:z7BAhU19usTApzlltO/X3lvqHLJj9KAMaGq7LBoCCZdlDAOo6s+pB4Z2L/2dQTfLrbimbPVx8ydN5thp8LFt7EkmYvZj/a9M++tqUxnaztObHDGkN31s7tJyoXkufBtsjBjb7T98pGp7crolfG7WJkf8UWrwaTIVpbRjqiBtbSuYW5weZztJKOAZZQABbVFiv0MPV83m1JqwBfH7B/KJ0Pc5x6G8bG/u7C5S+ColA0+pvw2kLHFO0mbu9bdsfz2S+FHN14blmijadZf2rk2yN9m2Ev9KyunGh1DmThvVLnPIboPzKEpgsH8LLhyUJ+1TK7HYLIaWHrnzVTyuH21CWlrV140ByXfBzwmKwgVKhl4OExxnnNo1Jj3Em0VVy3hS,iv:W5ZVo2GSd43M0e+NIWHJuKQ3hf3X8+0fq8eV8tyq94g=,tag:p15V+2aMMXK0+SAO79A39w==,type:str]
    identity.pub: ENC[AES256_GCM,data:kRIreN4W/vTN6ktKWVyFYOIIBuM7LrfQ/2mB2cJWkrcQuTwK7i/FdGbYfoPDOOKJSoQ4odQuouyN0a3T+iDB06nT5WTYzOLweSywr3i9B5Y7F/fXAMsiUli60wHhHl1MM97jx2QVoX4B2iErqFmodHLEvojTj8m620pk4tM3462THRMePds6yCa90oEp1GDogKkjXA0Hg/bnkyxnv+6nXC/4mvVfIYSDGvN5ZNAqmY6WY7yl3x0r4ZhOm+GAUnp8SgHXrhxjz66csJ7teA==,iv:NOQ5xhNusRoIeExnjc5SGvJKeDR75b3EZfgGbjCSmA0=,tag:ZyPc5bUqNtdWzKA56Ms8lA==,type:str]
    known_hosts: ENC[AES256_GCM,data:lmN0P8uh6VT8u0nxx9tw5qkbOSpk6jwo347SuRbux6UKdQ+zY++d7GYXUfG4lv6sAjh6bRk5sMztLKoWl9zY1ZGdf5plp6NscTfU/qFLHssF6WKT2Js6V31GGHz8eRHIE0RD8W7RWzS2Zg9cDAfLElqr4WOyQGghFUI0JB1rC0Czat6FMCdfsmoEh/4G91z83uxeeQpWNPNaCINsKTzEVuMDMZuTbNegzHtQ,iv:Cn7OagmbIsRitW2NZ0oM8oKblRMzrP3nsMdlXUbN2vs=,tag:ZL9n71G9kcqtcLX9/IdtSw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByY0J4MzkwM3pacnFoUXI2
            dkI2TlRkaUJmQUxOMEZMR0UyRE04TDRMUldRCkk0VnhubkduSEtGOEw4Qm1HR1pj
            Q0pvQ3pRTnd1emNRMzQxb0VNejU2ZlUKLS0tIDRCSTNOTTN1dy9MNmc2TS9oTGEw
            RnRKRi82OXVFMnJHU2NoOEYzN1BYYmMKpN4xSPXh5wmgF8SmoU9sNrULjATkIi65
            4zxcied6uMJxr5/zKs6zE5eqVpsO8CybIZ78aQ8OZxzAGm6puDvR+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T01:44:46Z"
    mac: ENC[AES256_GCM,data:Z6AgV2Bv2whaDgGCJEbgfVIKosqweaOjdfia1wIKzceYeryiNXTn7562OkWKAMRMAOfWp8blepHXM9vqcHbeOohcFgu3UW+1hAQNlsu8ZHeBSMhTG9mAt4N7KcOI5/RW35wCHHNSNjaHVXNCNSprdb0pWIo/6XPhynEZdLqTJvw=,iv:wbkJLYvgiSnBxkPrhFUnGva+QatifIAoJwBsxJ0hhCI=,tag:IsJhg0LNdx7xXEPkpPeS5A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
