apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GfrI4xOs8AtKLi053D+6NGCmMvoRKe0BvWQhWH++bP6YvGGBfX1C8pEiUF5vFan2vcFb/xBDffrVywZ8smIY0q2YRUPWRXUmGeYFz34CCkc7tiDWdsFKYKpctfETjvYoymzj3L5Fq8sBk3ibmClyfhlxQgV6kuBlQhTNc5V/WsLqpHFrywz3r5IBm2mNEzfFuGBc4t7fx59VpsId/GGEeqdHcIkOuZiYXx52YUtRS04Z+HOMb7CwnFA+ULm2FM4mVMuwkKezSbdr+IqcNJ2Ykcq668gAUq7cwxVNRLUeh5mMAS7KIOV76C/sBSgMgK5aXTYbshjy8Ll/fJCe+QPD/1DFZJR7FeEZLl6pGyXiIPE7XoVzRDa+CenBEcupPXfx,iv:Exp1/oFZnwd+IQ1hAk6LokzK+M6JAzEcEevfT1dom+Y=,tag:djVlO2JehTFge4kRUxe12A==,type:str]
    identity.pub: ENC[AES256_GCM,data:32KO1XHPgpzY51jqmtNkkPIArsFoT+WzhfkcBz7CnF9BNaljfmO0QobRHt3TtmwVL3Bk6FyvH61pGJaM5IxSwUIAKjWLAp5TntO4kjVRmJI8WFuAKAXdw1sxqsPEgPV5j1ADFDqchqb5h3rcANseAtz9Msbb/FyfZR4VY0TdGguC4cbNnNUn5wz7aGGsuP1L/rHGg1YsjyK7hrNbVSYOwXSoSQw0LHVXAuXIJsflCfzIRhbP352i9eIIn8vq5d9lWz3DPw/+5FqZtJ5kOw==,iv:SuUdGSFev5pN9KRAShuFcyraU64wvh+5Z+4l625+qIc=,tag:wn3B6e9UIekMtjRFSTebTA==,type:str]
    known_hosts: ENC[AES256_GCM,data:61OOGpzMoW0inqUwQCU64SULz8bkdMCOa15DHzy9WYIeAJktKIIrBIU9T62Ep0PdtNteKzjJiBgiM3TlLseuVpXfW8lJXjqjUNllGD3T2rPhz7SLZeQKcxqYs1OCa0TSVN6kZyE8r3rzuYhyTPy/q5xTnpiMSc5L8uCtXwT3+UIdFnwg1qh5PcVYrgCMsnMMGsf4X5IRp+Hcb4uu7wNimJBhFANP0Oe06VuH,iv:YETSB2lMB6Oa5ND13V/zitMZ8LWcyuqYZ8iyglOh5fw=,tag:vcgQtKII9KeBvHyFtsDoSw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdVpFY0RYNlZHR0NtM1lC
            bnpzMFdoN2RjL2UxZ25SVGhkTkMwOEUrNjN3Ci8wdnVSVzQ4UzNUa3daOGtQQzJ5
            ZHZUZVArait3c21QUnNqbG1JQjkyOWMKLS0tIDNGS2U4QjljR0c0azhJQWRIT1dp
            ZFpKR1BkblNPaDBNbnh4cXBiOW5CZEUK8TFIKTJIRGtV0Ujp484lFHQQTYCX+dE3
            il1qS+Q7+fh2RkP2nB5JoZ+jd4RvW+9+BIPdNGWl4M56t8lT6wQeUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T04:31:03Z"
    mac: ENC[AES256_GCM,data:4eNeJtCQveiWXsvmKHv9cG1d3jxTzuMC9uvv82mjc7MrunqQW5cmTXPLj4UZ+bVrk4GaYUOC98GnVM8l1vQvrUZuTsa1R2EZhdjH0ewkyGnFnkldO2PAPpG99MGLbd3ukhVMoZhdYZvcHpqIRb7aiwFEod2P1G+M84uwD0d0v4g=,iv:i2hCHT2HGOhMvGPlHqgod7F5vjafaYsalDq88jSqmf4=,tag:G+QmEwwE4ciCEfAgJO40jA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
