apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UoY1nMaoipcqe91WERKI2VjW0yOyhHWCv32+NATEnDlv5xVYGQ2CPNn5fzdqCWWPTAsjiUAVyeyR173N58/hockA4l7wLxkd0+IpeET0a3lauG3XTDehllkdUyIsWcit3qsQ9HKKkUFt2Foc7h/8ZJvIUBmfivqLL2hw6sZPCpgleynK9pruDzjtH/Lng/TrDAsjYJWbUX3RwQlfa12TpU7CRwnzGqjJLkeRZy4lCWuoB0SEryQ5ks2PjDnGEUM0aZRggxOpD07HFFVrOlBb/wB7Z0uJpJxCn+gjt0vkZ+Rq+nU/jRfiY8dbCm1MV51UEMAN+ybCj5ut8nvfBCMNA2XpUFnIayg+lxI6F31BunX3MdAeOS3SU77NveIUEFhg,iv:6eOich1VKN1viC0Mw+2aVU4QLpDXslLPGz81/sTJPJY=,tag:ojBgJ6eMO2c+C2RBSXvrGg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Xnr6huiG4w7llGaQxUkb1fBGvmgTSg+q7ST8jiS1hys5mhd1pTnXl7xSVxqI/muF251724OJP7Aqd1HCw83ViHOhLVFsPU5Bcv8yB6/N3wKESm6Mv2AkJGRochHtIkAonXJtfnWCFNf8mozgZxjYCP10f6PaaSI8dh8d4WSMMgLM087nIL4WsGqVEgZ+X52N8oivEBLB7wEkS5gRR3PTUq9qlKuCAD7p3JU4GPYJZD2F4m4vSCZjsrQINZHbJhDXHsMRlyBaV+9vl0MR1g==,iv:anCYCNp42cYp4X0pfBi0w4ArBZahJY6gXTIYJW+gQQw=,tag:4tqwM4Rpx3aunBL6SN69Mg==,type:str]
    known_hosts: ENC[AES256_GCM,data:opNHLnvQRW0X8wu5mPSr1gJ1J5RYw9BWNHdrXrxyR7sneROymfxcgtIVdVv64xY1FSz+CICGIK1hs3UyGTP0ETho8ru7SqKtLTNYiKzStLcrLPSZTOWFbmz4pWNOeusQqsXoaZ2ng05F0A+3R5FTuqO8QdbntZFImMAcClTEzJWaTmHKSCX9IQOktvyNCj47Z1gz0yiNKJd7U14sxd5TcPddGdNvBx/OZ6Z1,iv:aSbHN9SACwuvYRlRLrqlq+r+TO3DFLwwko35eC1oNGA=,tag:SpzZ/TkX/+IHry9Bc7NX1g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNi83Sm0zTVJDblpyMlY2
            Tkl2MW5LOE9sRUQyTU1OcWlxMTd4cU0zakFZCnFYblFBcVFjNUY2MTJPM3A3ZWl1
            aTlXb1R1L2JBY3poVEh4aHNkakNVZ2cKLS0tIHorYUlZZ1E4S04xdk5oUlNITmRY
            U0Fmbnlhc1MrdjBiS3l0ZVdTbmc0VncKgQIKXkXiicHB0/rqEdwOajPJh+yflCUL
            h0RCIvPYR70LbpEaECKNJOYg4vI0ekprVYbkrwPcLPJM4Pi+o7TAUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T03:05:21Z"
    mac: ENC[AES256_GCM,data:oIax3kNpAUoQorciCbPGPE/ZBgSt2nxhNBFM76t6i+MD2VjmJXyXpuGjZwndoiIAX9SbOd77itC8yFY/ySQ2mtCQKSSoq5wsGqJoGdOAiRNqn1bHt4tZiVs+x9GoJbd48FOOPquZlsblL46VRhNRk1xV3Lmi8jdR2c5gRzU38OQ=,iv:z71BwG3A8bgUTgdH+UrTqiirgdGWbRCiVLf9bjugXpg=,tag:w0+sbFi53n99DjwGdduN2w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
