apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: livekit-main
  namespace: livekit
spec:
  parentRefs:
    - name: envoy-external
      namespace: envoy
      sectionName: https
  hostnames:
    - "livekit.${INGRESS_URL}"
  rules:
    - backendRefs:
        - name: livekit-app-template
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: livekit-jwt
  namespace: livekit
spec:
  parentRefs:
    - name: envoy-external
      namespace: envoy
      sectionName: https
  hostnames:
    - "livekit.${INGRESS_URL}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /sfu/get
        - path:
            type: PathPrefix
            value: /healthz
        - path:
            type: PathPrefix
            value: /get_token
      backendRefs:
        - name: livekit-app-template-jwt
          port: 8080
