---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stunner-tls-ingress
  namespace: stunner-system
spec:
  ingressClassName: internal
  rules:
    - host: "turn2.${INGRESS_URL}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: udp-gateway
                port:
                  number: 5349
  tls:
    - secretName:
      hosts:
        - "turn2.${INGRESS_URL}"
