apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: stunner-gatewayclass
spec:
  controllerName: "stunner.l7mp.io/gateway-operator"
  parametersRef:
    group: "stunner.l7mp.io"
    kind: GatewayConfig
    name: stunner-gatewayconfig
    namespace: stunner-system
  description: "STUNner is a WebRTC ingress gateway for Kubernetes"

---
apiVersion: stunner.l7mp.io/v1
kind: GatewayConfig
metadata:
  name: stunner-gatewayconfig
  namespace: stunner-system
spec:
  logLevel: "all:DEBUG,turn:INFO"
  realm: stunner.l7mp.io
  authType: ephemeral
  sharedSecret: ${LK_TURN_SECRET}
  loadBalancerServiceAnnotations:
    metallb.io/ip-allocated-from-pool: main
    metallb.io/loadBalancerIPs: ${STUNNER_UDP_IP}
    metallb.io/allow-shared-ip: stunner
    #coredns.io/hostname: turn.${INGRESS_URL}

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: udp-gateway
  namespace: stunner-system
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: udp-listener
      port: 3478
      protocol: TURN-UDP
    - name: tls
      port: 5349
      protocol: TURN-TLS
      tls:
        certificateRefs:
          - kind: Secret
            name: certificate-issuer-domain-0-wildcard
            namespace: clusterissuer

---
apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: livekit-media-plane
  namespace: stunner-system
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - name: livekit-server
          namespace: livekit
