apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gatus-route
spec:
  parentRefs:
    - name: envoy-internal
  hostnames:
    - "gatus.${INGRESS_URL}"
  rules:
    - backendRefs:
        - name: gatus
          port: 8080
