apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gatus-route
  namespace: gatus
  gethomepage.dev/enabled: "true"
  gethomepage.dev/description: Endpoint monitoring
  gethomepage.dev/group: Default
  #gethomepage.dev/icon: emby.png
  gethomepage.dev/name: Gatus
  gethomepage.dev/widget.type: "gatus"
  gethomepage.dev/instance: "internal" # optional
spec:
  parentRefs:
    - name: envoy-internal
      namespace: envoy
      sectionName: https
  hostnames:
    - "gatus.${INGRESS_URL}"
  rules:
    - backendRefs:
        - name: gatus
          port: 8080
