apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homepage-external
  namespace: homepage-external
spec:
  parentRefs:
    - name: envoy-external
      namespace: envoy
      sectionName: https
  hostnames:
    - "${INGRESS_URL}"
  rules:
    - backendRefs:
        - name: homepage-external
          port: 10352
